"""Auto-fix service for delivery review failures.

When the generated APP fails delivery review, this service analyzes the specific
failures and applies targeted fixes to the HTML before re-reviewing.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

from regent.application.delivery_review_service import (
    DeliveryReviewCheck,
    review_html_for_delivery,
)


@dataclass
class AutoFixResult:
    """Result of auto-fix attempt."""

    fixed: bool
    html: str
    fixes_applied: list[str]
    remaining_issues: list[str]
    attempts: int


# Patterns for demo/placeholder detection
_DEMO_PATTERNS = [
    r"lorem\s+ipsum",
    r"this\s+is\s+a\s+demo",
    r"demo\s+only",
    r"sample\s+placeholder",
    r"placeholder\s+text",
    r"example\s+content",
]

# Minimum CSS to inject if missing
_MINIMAL_CSS = """
/* Auto-generated by Regent Core */
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; }
main { max-width: 1200px; margin: 0 auto; padding: 2rem; background: white; min-height: 100vh; }
header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 2rem; margin-bottom: 2rem; border-radius: 8px; }
h1 { font-size: 2rem; margin-bottom: 0.5rem; }
h2 { font-size: 1.5rem; margin: 1.5rem 0 1rem; color: #667eea; }
p { margin-bottom: 1rem; }
.card { background: #f9f9f9; padding: 1.5rem; margin: 1rem 0; border-radius: 8px; border-left: 4px solid #667eea; }
.btn { display: inline-block; padding: 0.75rem 1.5rem; background: #667eea; color: white; text-decoration: none; border-radius: 6px; cursor: pointer; border: none; font-size: 1rem; }
.btn:hover { background: #5568d3; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; margin: 2rem 0; }
"""


def _has_main_tag(html: str) -> bool:
    return bool(re.search(r"<main[\s>]", html, re.I))


def _has_data_regent_event(html: str) -> bool:
    return "data-regent-event" in html


def _has_stylesheet(html: str) -> bool:
    return bool(re.search(r"<style\b", html, re.I)) or bool(
        re.search(r'<link[^>]*rel\s*=\s*["\']stylesheet["\']', html, re.I)
    )


def _get_style_length(html: str) -> int:
    match = re.search(r"<style[^>]*>(.*?)</style>", html, re.I | re.S)
    return len(match.group(1)) if match else 0


def _has_demo_content(html: str) -> bool:
    text = re.sub(r"<[^>]+>", " ", html).lower()
    return any(re.search(p, text) for p in _DEMO_PATTERNS)


def _extract_first_deliverable(acceptance_contract: dict[str, Any] | None) -> str:
    if not acceptance_contract:
        return ""
    return str(acceptance_contract.get("first_deliverable") or "")


def _deliverable_keywords_present(html: str, deliverable: str) -> bool:
    if not deliverable:
        return True
    text = re.sub(r"<[^>]+>", " ", html).lower()
    # Extract key nouns from deliverable (simple heuristic)
    words = [w.lower() for w in re.findall(r"[\w\u4e00-\u9fff]+", deliverable) if len(w) > 1]
    stop_words = {"the", "a", "an", "is", "are", "was", "were", "be", "been", "being"}
    keywords = [w for w in words if w not in stop_words][:5]
    if not keywords:
        return True
    hits = sum(1 for kw in keywords if kw in text)
    return hits >= max(1, len(keywords) // 2)


def _add_main_wrapper(html: str) -> str:
    """Wrap content in <main> if missing."""
    if _has_main_tag(html):
        return html
    # Find body content and wrap it
    body_match = re.search(r"<body[^>]*>(.*?)</body>", html, re.I | re.S)
    if body_match:
        inner = body_match.group(1).strip()
        # Wrap all body content in <main>
        new_inner = f"<main>\n{inner}\n</main>"
        return html[: body_match.start(1)] + new_inner + html[body_match.end(1) :]
    return html


def _add_data_regent_event(html: str) -> str:
    """Add data-regent-event to first interactive element."""
    if _has_data_regent_event(html):
        return html
    # Find first button, link, or interactive element
    for pattern in [r"<button", r"<a\s+href", r"<input", r"<select"]:
        match = re.search(pattern, html, re.I)
        if match:
            # Find the end of the opening tag
            tag_end = html.index(">", match.start())
            # Insert attribute before >
            return html[:tag_end] + ' data-regent-event="click"' + html[tag_end:]
    # If no interactive element, add to body
    body_match = re.search(r"<body", html, re.I)
    if body_match:
        tag_end = html.index(">", body_match.start())
        return html[:tag_end] + ' data-regent-event="load"' + html[tag_end:]
    return html


def _inject_css(html: str, min_chars: int = 220) -> str:
    """Add minimum CSS if missing or insufficient."""
    if _has_stylesheet(html) and _get_style_length(html) >= min_chars:
        return html
    # Find </head> or <body> to inject style
    head_match = re.search(r"</head>", html, re.I)
    if head_match:
        inject_pos = head_match.start()
        style_block = f"<style>{_MINIMAL_CSS}</style>\n"
        return html[:inject_pos] + style_block + html[inject_pos:]
    body_match = re.search(r"<body", html, re.I)
    if body_match:
        inject_pos = body_match.start()
        style_block = f"<style>{_MINIMAL_CSS}</style>\n"
        return html[:inject_pos] + style_block + html[inject_pos:]
    # Fallback: prepend
    return f"<style>{_MINIMAL_CSS}</style>\n{html}"


def _remove_demo_content(html: str) -> str:
    """Remove or replace demo/placeholder text."""
    if not _has_demo_content(html):
        return html
    text = re.sub(r"<[^>]+>", " ", html).lower()
    for pattern in _DEMO_PATTERNS:
        match = re.search(pattern, text)
        if match:
            # Find and replace the paragraph containing demo text
            para_match = re.search(r"<p[^>]*>.*?" + pattern + r".*?</p>", html, re.I | re.S)
            if para_match:
                html = html[: para_match.start()] + html[para_match.end() :]
    return html


def _enhance_deliverable_content(html: str, deliverable: str) -> str:
    """Add deliverable keywords to content if missing."""
    if _deliverable_keywords_present(html, deliverable):
        return html
    # Find main content area or add a section
    main_match = re.search(r"<main[^>]*>(.*?)</main>", html, re.I | re.S)
    if main_match:
        inner = main_match.group(1)
        # Add a card with deliverable info
        card = f'\n<div class="card">\n<h2>核心功能</h2>\n<p>{deliverable}</p>\n</div>\n'
        new_inner = inner + card
        return html[: main_match.start(1)] + new_inner + html[main_match.end(1) :]
    # Fallback: add before </body>
    body_end = re.search(r"</body>", html, re.I)
    if body_end:
        card = f'<main><div class="card"><h2>核心功能</h2><p>{deliverable}</p></div></main>\n'
        return html[: body_end.start()] + card + html[body_end.start() :]
    return html


class AutoFixService:
    """Automatically fix delivery review failures."""

    MAX_ATTEMPTS = 3

    def __init__(self) -> None:
        self._fix_log: list[str] = []

    def fix(
        self,
        html: str,
        *,
        acceptance_contract: dict[str, Any] | None = None,
        success_criteria: dict[str, Any] | None = None,
        failed_checks: list[DeliveryReviewCheck] | None = None,
    ) -> AutoFixResult:
        """Attempt to fix HTML based on failed delivery review checks."""
        fixes_applied: list[str] = []
        remaining_issues: list[str] = []
        attempts = 0

        for attempt in range(self.MAX_ATTEMPTS):
            attempts += 1
            current_html = html

            # Apply targeted fixes based on failed checks
            if failed_checks:
                for check in failed_checks:
                    if check.name == "semantic-main" and not check.passed:
                        html = _add_main_wrapper(html)
                        if html != current_html:
                            fixes_applied.append("added <main> wrapper")
                    elif check.name == "observation-hook" and not check.passed:
                        html = _add_data_regent_event(html)
                        if html != current_html:
                            fixes_applied.append("added data-regent-event")
                    elif check.name in ("stylesheet-present", "stylesheet-substance") and not check.passed:
                        html = _inject_css(html)
                        if html != current_html:
                            fixes_applied.append("injected minimum CSS")
                    elif check.name == "forbid-demo-copy" and not check.passed:
                        html = _remove_demo_content(html)
                        if html != current_html:
                            fixes_applied.append("removed demo content")
                    elif check.name == "goal-first-deliverable" and not check.passed:
                        deliverable = _extract_first_deliverable(acceptance_contract)
                        html = _enhance_deliverable_content(html, deliverable)
                        if html != current_html:
                            fixes_applied.append("enhanced deliverable content")

            # Re-review after fixes
            review = review_html_for_delivery(
                html,
                acceptance_contract=acceptance_contract,
                success_criteria=success_criteria,
            )

            if review.passed:
                return AutoFixResult(
                    fixed=True,
                    html=html,
                    fixes_applied=fixes_applied,
                    remaining_issues=[],
                    attempts=attempts,
                )

            # Update failed checks for next iteration
            failed_checks = [c for c in review.checks if not c.passed]
            if not failed_checks:
                break

        # Exhausted attempts - report remaining issues
        if failed_checks:
            remaining_issues = [f"{c.name}: {c.detail}" for c in failed_checks]

        return AutoFixResult(
            fixed=False,
            html=html,
            fixes_applied=fixes_applied,
            remaining_issues=remaining_issues,
            attempts=attempts,
        )
